### ISSUE TITLE
Start failed: "ERR! PuppetWeb Error: Server terminated early with status 127"

### ISSUE THREAD

**Issue by cncoder** [zixia/wechaty#7]
=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...

info Wechaty init() with version: 0.0.11
verb PuppetWeb init()
verb PuppetWeb initAttach()
verb PuppetWeb initAttach done: true
verb PuppetWeb initBrowser
verb Browser init()
verb Browser initDriver()
sill Browser phantomjs binary: /data/www/default/wechaty/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
verb Browser initDriver() done
verb Browser open()ing at https://wx.qq.com
ERR! PuppetWeb Error: Server terminated early with status 127
ERR! PuppetWeb     at Error (native)
ERR! PuppetWeb     at /data/www/default/wechaty/node_modules/selenium-webdriver/remote/index.js:242:20
ERR! PuppetWeb     at ManagedPromise.invokeCallback_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
ERR! PuppetWeb     at TaskQueue.execute_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
ERR! PuppetWeb     at TaskQueue.executeNext_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
ERR! PuppetWeb     at asyncRun (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
ERR! PuppetWeb     at /data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:639:7
ERR! PuppetWeb     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! PuppetWeb From: Task: WebDriver.createSession()
ERR! PuppetWeb     at Function.createSession (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
ERR! PuppetWeb     at Driver (/data/www/default/wechaty/node_modules/selenium-webdriver/phantomjs.js:192:38)
ERR! PuppetWeb     at Builder.build (/data/www/default/wechaty/node_modules/selenium-webdriver/builder.js:479:16)
ERR! PuppetWeb     at Browser.getPhantomJsDriver (/data/www/default/wechaty/src/puppet-web-browser.js:79:6)
ERR! PuppetWeb     at Browser.initDriver (/data/www/default/wechaty/src/puppet-web-browser.js:54:26)
ERR! PuppetWeb     at Browser.init (/data/www/default/wechaty/src/puppet-web-browser.js:28:17)
ERR! PuppetWeb     at PuppetWeb.initBrowser (/data/www/default/wechaty/src/puppet-web.js:83:25)
ERR! PuppetWeb     at initAttach.then.r (/data/www/default/wechaty/src/puppet-web.js:50:19)
ERR! PuppetWeb     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! PuppetWeb     at Function.Module.runMain (module.js:577:11)
ERR! PuppetWeb From: Task: WebDriver.navigate().to(https://wx.qq.com)
ERR! PuppetWeb     at Driver.schedule (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
ERR! PuppetWeb     at Navigation.to (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
ERR! PuppetWeb     at Driver.get (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:795:28)
ERR! PuppetWeb     at Browser.open (/data/www/default/wechaty/src/puppet-web-browser.js:43:24)
ERR! PuppetWeb     at initDriver.then.r (/data/www/default/wechaty/src/puppet-web-browser.js:31:19)
ERR! PuppetWeb     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! PuppetWeb     at Function.Module.runMain (module.js:577:11)
ERR! PuppetWeb     at startup (node.js:160:18)
ERR! PuppetWeb     at node.js:456:3
ERR! PuppetWeb  Error: Server terminated early with status 127
ERR! PuppetWeb     at Error (native)
ERR! PuppetWeb     at /data/www/default/wechaty/node_modules/selenium-webdriver/remote/index.js:242:20
ERR! PuppetWeb     at ManagedPromise.invokeCallback_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
ERR! PuppetWeb     at TaskQueue.execute_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
ERR! PuppetWeb     at TaskQueue.executeNext_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
ERR! PuppetWeb     at asyncRun (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
ERR! PuppetWeb     at /data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:639:7
ERR! PuppetWeb     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! PuppetWeb From: Task: WebDriver.createSession()
ERR! PuppetWeb     at Function.createSession (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
ERR! PuppetWeb     at Driver (/data/www/default/wechaty/node_modules/selenium-webdriver/phantomjs.js:192:38)
ERR! PuppetWeb     at Builder.build (/data/www/default/wechaty/node_modules/selenium-webdriver/builder.js:479:16)
ERR! PuppetWeb     at Browser.getPhantomJsDriver (/data/www/default/wechaty/src/puppet-web-browser.js:79:6)
ERR! PuppetWeb     at Browser.initDriver (/data/www/default/wechaty/src/puppet-web-browser.js:54:26)
ERR! PuppetWeb     at Browser.init (/data/www/default/wechaty/src/puppet-web-browser.js:28:17)
ERR! PuppetWeb     at PuppetWeb.initBrowser (/data/www/default/wechaty/src/puppet-web.js:83:25)
ERR! PuppetWeb     at initAttach.then.r (/data/www/default/wechaty/src/puppet-web.js:50:19)
ERR! PuppetWeb     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! PuppetWeb     at Function.Module.runMain (module.js:577:11)
ERR! PuppetWeb From: Task: WebDriver.navigate().to(https://wx.qq.com)
ERR! PuppetWeb     at Driver.schedule (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
ERR! PuppetWeb     at Navigation.to (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
ERR! PuppetWeb     at Driver.get (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:795:28)
ERR! PuppetWeb     at Browser.open (/data/www/default/wechaty/src/puppet-web-browser.js:43:24)
ERR! PuppetWeb     at initDriver.then.r (/data/www/default/wechaty/src/puppet-web-browser.js:31:19)
ERR! PuppetWeb     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! PuppetWeb     at Function.Module.runMain (module.js:577:11)
ERR! PuppetWeb     at startup (node.js:160:18)
ERR! PuppetWeb     at node.js:456:3
ERR! Bot Error: Server terminated early with status 127
ERR! Bot     at Error (native)
ERR! Bot     at /data/www/default/wechaty/node_modules/selenium-webdriver/remote/index.js:242:20
ERR! Bot     at ManagedPromise.invokeCallback_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
ERR! Bot     at TaskQueue.execute_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
ERR! Bot     at TaskQueue.executeNext_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
ERR! Bot     at asyncRun (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
ERR! Bot     at /data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:639:7
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot From: Task: WebDriver.createSession()
ERR! Bot     at Function.createSession (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
ERR! Bot     at Driver (/data/www/default/wechaty/node_modules/selenium-webdriver/phantomjs.js:192:38)
ERR! Bot     at Builder.build (/data/www/default/wechaty/node_modules/selenium-webdriver/builder.js:479:16)
ERR! Bot     at Browser.getPhantomJsDriver (/data/www/default/wechaty/src/puppet-web-browser.js:79:6)
ERR! Bot     at Browser.initDriver (/data/www/default/wechaty/src/puppet-web-browser.js:54:26)
ERR! Bot     at Browser.init (/data/www/default/wechaty/src/puppet-web-browser.js:28:17)
ERR! Bot     at PuppetWeb.initBrowser (/data/www/default/wechaty/src/puppet-web.js:83:25)
ERR! Bot     at initAttach.then.r (/data/www/default/wechaty/src/puppet-web.js:50:19)
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot     at Function.Module.runMain (module.js:577:11)
ERR! Bot From: Task: WebDriver.navigate().to(https://wx.qq.com)
ERR! Bot     at Driver.schedule (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
ERR! Bot     at Navigation.to (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
ERR! Bot     at Driver.get (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:795:28)
ERR! Bot     at Browser.open (/data/www/default/wechaty/src/puppet-web-browser.js:43:24)
ERR! Bot     at initDriver.then.r (/data/www/default/wechaty/src/puppet-web-browser.js:31:19)
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot     at Function.Module.runMain (module.js:577:11)
ERR! Bot     at startup (node.js:160:18)
ERR! Bot     at node.js:456:3
ERR! Bot  init() fail: %s Error: Server terminated early with status 127
ERR! Bot     at Error (native)
ERR! Bot     at /data/www/default/wechaty/node_modules/selenium-webdriver/remote/index.js:242:20
ERR! Bot     at ManagedPromise.invokeCallback_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:1379:14)
ERR! Bot     at TaskQueue.execute_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2913:14)
ERR! Bot     at TaskQueue.executeNext_ (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2896:21)
ERR! Bot     at asyncRun (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:2775:27)
ERR! Bot     at /data/www/default/wechaty/node_modules/selenium-webdriver/lib/promise.js:639:7
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot From: Task: WebDriver.createSession()
ERR! Bot     at Function.createSession (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
ERR! Bot     at Driver (/data/www/default/wechaty/node_modules/selenium-webdriver/phantomjs.js:192:38)
ERR! Bot     at Builder.build (/data/www/default/wechaty/node_modules/selenium-webdriver/builder.js:479:16)
ERR! Bot     at Browser.getPhantomJsDriver (/data/www/default/wechaty/src/puppet-web-browser.js:79:6)
ERR! Bot     at Browser.initDriver (/data/www/default/wechaty/src/puppet-web-browser.js:54:26)
ERR! Bot     at Browser.init (/data/www/default/wechaty/src/puppet-web-browser.js:28:17)
ERR! Bot     at PuppetWeb.initBrowser (/data/www/default/wechaty/src/puppet-web.js:83:25)
ERR! Bot     at initAttach.then.r (/data/www/default/wechaty/src/puppet-web.js:50:19)
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot     at Function.Module.runMain (module.js:577:11)
ERR! Bot From: Task: WebDriver.navigate().to(https://wx.qq.com)
ERR! Bot     at Driver.schedule (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
ERR! Bot     at Navigation.to (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
ERR! Bot     at Driver.get (/data/www/default/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:795:28)
ERR! Bot     at Browser.open (/data/www/default/wechaty/src/puppet-web-browser.js:43:24)
ERR! Bot     at initDriver.then.r (/data/www/default/wechaty/src/puppet-web-browser.js:31:19)
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot     at Function.Module.runMain (module.js:577:11)
ERR! Bot     at startup (node.js:160:18)
ERR! Bot     at node.js:456:3
verb PuppetWeb quit()
WARN PuppetWeb quit() without bridge
WARN PuppetWeb quit() without server

**Comment by zixia** [comment]
wechaty support platforms include linux & win32 & mac.

Current version is passed all the ci environments and run no problem.

In order to solve your problem, I have two suggestions:

1. check if your phantomjs binary work correct and can be found by nodejs.  
    ```
    sill Browser phantomjs binary: /data/www/default/wechaty/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
    ```
    
    because:
    
    ```
    127 in bash means: "command not found", illegal_command, possible problem with $PATH or a typo.
    ```
2. use npm version of wechaty instead.  
    ```shell
    npm install wechaty --save
    ```

please feel free to let me know if you still have any problem.

**Comment by cncoder** [comment]
I unable use it now. I will check it next month~~Thanks

**Comment by zixia** [comment]
@cncoder strange. everything is ok in my box. 

can you install the last npm version, then try again?

**Comment by cncoder** [comment]
Now i can use it normally. But i doubt that it cause by the permission under the windows, or cause by the agency.

**Comment by zixia** [comment]
great. cheers!
